version: '3'
services:
  raleydb:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=Root@123
      - MYSQL_DATABASE=raley
    networks:
      - raley
    ports:
      - "3307:3306"
  raleyregistration:
    image: registration:latest
    ports:
      - "8088:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://raleydb:3306/raley?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Root@123"
    networks:
      - raley
    depends_on:
      - raleydb
  raleylogin:
    image: login:latest
    ports:
      - "8089:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://raleydb:3306/raley?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Root@123"
    networks:
      - raley
    depends_on:
      - raleydb
  raleyEureka:
    image: eureka:latest
    ports:
      - "8086:8761"
    networks:
      - raley

networks:
  raley: 